name: My Workflow
on : push
jobs:
    job1:
        runs-on: ubauntu-latest
        steps:
            - name: step1
              run: echo "hello from step1"
            - name: step2
              run: echo "hello from step2"
     job2:
        runs-on: ubauntu-latest
        steps:
            - name: final step
              run: echo "hello from final step"
            - name: Another Step
              run: echo "Workflow executed again"
            

